### ISSUE TITLE
Python 3.5 and pytest-openfiles/pytest-doctestplus Conda packages 

### ISSUE THREAD

**Issue by Marie-Terrell** [astropy/conda-channel-astropy#181]
I'm sorry if this is the wrong place to be reporting this.

**Issue**
The pytest-openfiles and pytest-doctestplus no longer support Python 3.5 and require newer versions of pytest, but the run requirements for the Conda packages have not been updated. This has been forcing us to add version caps when we run our package tests. 

**Steps to Reproduce**
If I install the latest Conda package for either of the above (0.5.0 and 0.7.0 respectively) with Python 3.5, the first place I run into issues is something along these lines:
`$> pytest --trace-config
pluggy.manager.PluginValidationError: Plugin 'pytest_doctestplus' could not be loaded: (pytest 3.8.1 (/path-to-environment/lib/python3.5/site-packages), Requirement.parse('pytest>=4.0'))!`

**Comment by mwcraig** [comment]
Thanks for reporting this. I'll take a look at updating the recipes. Looks like at least `pytest-openfiles` has been waiting on an update on conda-forge (where we copy our conda packages from) for a couple of months.

I gather that what you need is for the python version restrictions to be clearly indicated so that you don't end up with a package installed that doesn't work, correct?

**Comment by Marie-Terrell** [comment]
Yeah. Basically, the meta.yaml for the recipes just need the minimum version restrictions added for Python and pytest. I was unsure who I should be reporting the issue to as I have been installing from the default channels, but the recipes seem to be shared in a number of places

**Comment by mwcraig** [comment]
I've fixed both packages on conda-forge, and they should get copied over to the astropy conda channel in about an hour but will leave this open until I can confirm that the new packages have actually copied over.

**Comment by Marie-Terrell** [comment]
Thank you so much for the quick response and fix for this!

**Comment by mwcraig** [comment]
No problem! It should be fixed now but feel free to reopen if it isn't.

**Comment by Marie-Terrell** [comment]
Thank you for your help. Python 3.5 is now not trying to install the new packages. I will note through that the original build of the package (pytest-doctestplus-0.7.0-pyh9f0ad1d_0.tar.bz2) will need to be removed from the Conda-forge and Astropy channels. If not, it will still get picked up. 
Defaults still has both packages with issues, but I've reported that here: ContinuumIO/anaconda-issues#11864.

**Comment by mwcraig** [comment]
I've removed from the astropy conda channel and marked it as broken on conda-forge  -- please let me know if it is still failing for you.

**Comment by mwcraig** [comment]
Closing, because I think this is fixed -- but if not, please feel free to reopen.
